version: "3"
services:
  mysql1:
    image: mysql:latest
    container_name: 353_project_simple
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: simple
    volumes:
      - db:/var/lib/mysql
      - ./team-init.sql:/docker-entrypoint-initdb.d/team-init.sql

volumes:
  db:
    driver: local
