version: "3"
services:
  mysql1:
    image: mysql:5.7.31
    container_name: db1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project_simple
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
